# Generated by Django 5.2.7 on 2025-10-02 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competition_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('competition_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('competition_region', models.CharField(blank=True, default='', max_length=255)),
                ('market_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competition',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type_id', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('oid', models.IntegerField(blank=True, default=0, null=True)),
                ('tree', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('event_country_code', models.CharField(blank=True, default='', max_length=10)),
                ('event_timezone', models.CharField(blank=True, default='', max_length=50)),
                ('event_open_date', models.DateTimeField(blank=True, null=True)),
                ('common_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_fancy', models.BooleanField(default=True)),
                ('provider_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_name', models.CharField(blank=True, default='', max_length=255)),
                ('tv_url', models.URLField(blank=True, default='', max_length=500)),
                ('score_iframe_url', models.URLField(blank=True, default='', max_length=500)),
                ('market_ids', models.JSONField(blank=True, default=list)),
                ('market_count', models.IntegerField(default=0)),
                ('selections', models.JSONField(blank=True, default=list)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sports.competition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sports.sport')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='sports.sport'),
        ),
    ]
